// Code generated by "stringer -type=SectionType"; DO NOT EDIT

package item

import "fmt"

const _SectionType_name = "SectionUNKNOWN2SectionSTRINGSSectionUNKNOWN4SectionDefinitionsSectionUNKNOWN5SectionUNKNOWN6SectionUNKNOWN7SectionUNKNOWN1SectionTOBJSectionUNKNOWN9SectionOBJSectionUNKNOWN10SectionINSTSectionLODSectionUNKNOWN8SectionUNKNOWN3"

var _SectionType_map = map[SectionType]string{
	7:          _SectionType_name[0:15],
	16:         _SectionType_name[15:29],
	21:         _SectionType_name[29:44],
	74:         _SectionType_name[44:62],
	366926375:  _SectionType_name[62:77],
	637823035:  _SectionType_name[77:92],
	975627745:  _SectionType_name[92:107],
	1733268304: _SectionType_name[107:122],
	1991296364: _SectionType_name[122:133],
	2182960161: _SectionType_name[133:148],
	2195127427: _SectionType_name[148:158],
	3430328684: _SectionType_name[158:174],
	3461354627: _SectionType_name[174:185],
	3545841574: _SectionType_name[185:195],
	3649811809: _SectionType_name[195:210],
	3805007828: _SectionType_name[210:225],
}

func (i SectionType) String() string {
	if str, ok := _SectionType_map[i]; ok {
		return str
	}
	return fmt.Sprintf("SectionType(%d)", i)
}
