// Code generated by "stringer -type=FieldType"; DO NOT EDIT

package item

import "fmt"

const (
	_FieldType_name_0 = "FieldUint32FieldFlags32"
	_FieldType_name_1 = "FieldFloat32"
	_FieldType_name_2 = "FieldVec4f"
	_FieldType_name_3 = "FieldJenkins"
)

var (
	_FieldType_index_0 = [...]uint8{0, 11, 23}
	_FieldType_index_1 = [...]uint8{0, 12}
	_FieldType_index_2 = [...]uint8{0, 10}
	_FieldType_index_3 = [...]uint8{0, 12}
)

func (i FieldType) String() string {
	switch {
	case 20 <= i && i <= 21:
		i -= 20
		return _FieldType_name_0[_FieldType_index_0[i]:_FieldType_index_0[i+1]]
	case i == 33:
		return _FieldType_name_1
	case i == 51:
		return _FieldType_name_2
	case i == 74:
		return _FieldType_name_3
	default:
		return fmt.Sprintf("FieldType(%d)", i)
	}
}
