// Code generated by "stringer -type=SectionType"; DO NOT EDIT

package item

import "fmt"

const _SectionType_name = "SectionUNKNOWN10SectionSTRINGSSectionUNKNOWN11SectionUNKNOWN12SectionTypeRefCExtensionDefExplosionEffectCMloInstanceDefCMloRoomDefCMloArchetypeDefCExtensionDefAudioCollisionSettingsCExtensionDefWindDisturbanceCExtensionDefAudioEmitterCExtensionDefLightEffectCExtensionDefBuoyancyCMloTimeCycleModifierPhVerletClothCustomBoundsCExtensionDefParticleEffectSectionUNKNOWN7SectionUNKNOWN2SectionUNKNOWN1CTimeCycleModifierCCarGenCExtensionDefDoorSectionUNKNOWN3CTimeArchetypeDefSectionUNKNOWN4CExtensionDefLadderCBaseArchetypeDefCExtensionDefProcObjectCMloPortalDefCExtensionDefSpawnPointOverrideCExtensionDefLightShaftSectionUNKNOWN5CExtensionDefSpawnPointSectionUNKNOWN8CEntityDefCMapDataCMloEntitySetCMapTypesSectionUNKNOWN9CExtensionDefExpressionSectionUNKNOWN6CLightAttrDef"

var _SectionType_map = map[SectionType]string{
	7:          _SectionType_name[0:16],
	16:         _SectionType_name[16:30],
	21:         _SectionType_name[30:46],
	51:         _SectionType_name[46:62],
	74:         _SectionType_name[62:76],
	104349545:  _SectionType_name[76:104],
	164374718:  _SectionType_name[104:119],
	186126833:  _SectionType_name[119:130],
	273704021:  _SectionType_name[130:146],
	366926375:  _SectionType_name[146:181],
	569228403:  _SectionType_name[181:209],
	637823035:  _SectionType_name[209:234],
	663891011:  _SectionType_name[234:258],
	749982947:  _SectionType_name[258:279],
	807246248:  _SectionType_name[279:300],
	847348117:  _SectionType_name[300:325],
	975627745:  _SectionType_name[325:352],
	975711773:  _SectionType_name[352:367],
	1185771007: _SectionType_name[367:382],
	1701774085: _SectionType_name[382:397],
	1733268304: _SectionType_name[397:415],
	1860713439: _SectionType_name[415:422],
	1965932561: _SectionType_name[422:439],
	1980345114: _SectionType_name[439:454],
	1991296364: _SectionType_name[454:471],
	2085051229: _SectionType_name[471:486],
	2182960161: _SectionType_name[486:505],
	2195127427: _SectionType_name[505:522],
	2565191912: _SectionType_name[522:545],
	2572186314: _SectionType_name[545:558],
	2716862120: _SectionType_name[558:589],
	2718997053: _SectionType_name[589:612],
	2741784237: _SectionType_name[612:627],
	3300062776: _SectionType_name[627:650],
	3430328684: _SectionType_name[650:665],
	3461354627: _SectionType_name[665:675],
	3545841574: _SectionType_name[675:683],
	3601308153: _SectionType_name[683:696],
	3649811809: _SectionType_name[696:705],
	3805007828: _SectionType_name[705:720],
	3870521079: _SectionType_name[720:743],
	3985044770: _SectionType_name[743:758],
	4115341947: _SectionType_name[758:771],
}

func (i SectionType) String() string {
	if str, ok := _SectionType_map[i]; ok {
		return str
	}
	return fmt.Sprintf("SectionType(%d)", i)
}
